export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const INCREMENT_PRODUCT = 'INCREMENT_PRODUCT';
export const DECREMENT_PRODUCT = 'DECREMENT_PRODUCT';
export const SET_ON_SALE_FILTER = 'SET_ON_SALE_FILTER';
export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';
